# Generated by Django 3.2.2 on 2021-05-11 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pratice_Problems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('long_des', models.TextField(null=True)),
                ('image', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Test_Case_Output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputt1', models.TextField(null=True)),
                ('inputt2', models.TextField(null=True)),
                ('inputt3', models.TextField(null=True)),
                ('inputt4', models.TextField(null=True)),
                ('inputt5', models.TextField(null=True)),
                ('inputt6', models.TextField(null=True)),
                ('inputt7', models.TextField(null=True)),
                ('inputt8', models.TextField(null=True)),
                ('inputt9', models.TextField(null=True)),
                ('inputt10', models.TextField(null=True)),
                ('ex_outputt1', models.TextField(null=True)),
                ('ex_outputt2', models.TextField(null=True)),
                ('ex_outputt3', models.TextField(null=True)),
                ('ex_outputt4', models.TextField(null=True)),
                ('ex_outputt5', models.TextField(null=True)),
                ('ex_outputt6', models.TextField(null=True)),
                ('ex_outputt7', models.TextField(null=True)),
                ('ex_outputt8', models.TextField(null=True)),
                ('ex_outputt9', models.TextField(null=True)),
                ('ex_outputt10', models.TextField(null=True)),
                ('Pratice_Problems_Id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Compiler.pratice_problems')),
            ],
        ),
        migrations.CreateModel(
            name='User_Pratice_Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_for_problem', models.TextField(null=True)),
                ('point_scored', models.IntegerField(null=True)),
                ('outputt1', models.TextField(null=True)),
                ('outputt2', models.TextField(null=True)),
                ('outputt3', models.TextField(null=True)),
                ('outputt4', models.TextField(null=True)),
                ('outputt5', models.TextField(null=True)),
                ('outputt6', models.TextField(null=True)),
                ('outputt7', models.TextField(null=True)),
                ('outputt8', models.TextField(null=True)),
                ('outputt9', models.TextField(null=True)),
                ('outputt10', models.TextField(null=True)),
                ('solution_to_problem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Compiler.pratice_problems')),
                ('test_case_to_problem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Compiler.test_case_output')),
                ('usr_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
