# Generated by Django 3.2.2 on 2021-05-11 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compiler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pratice_problems',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
