# Generated by Django 3.2.2 on 2021-05-11 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compiler', '0003_auto_20210512_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pratice_problems',
            name='ex_outputt1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pratice_problems',
            name='ex_outputt10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pratice_problems',
            name='ex_outputt2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pratice_problems',
            name='ex_outputt3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pratice_problems',
            name='ex_outputt4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pratice_problems',
            name='ex_outputt5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pratice_problems',
            name='ex_outputt6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pratice_problems',
            name='ex_outputt7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pratice_problems',
            name='ex_outputt8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pratice_problems',
            name='ex_outputt9',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pratice_problems',
            name='inputt1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pratice_problems',
            name='inputt10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pratice_problems',
            name='inputt2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pratice_problems',
            name='inputt3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pratice_problems',
            name='inputt4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pratice_problems',
            name='inputt5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pratice_problems',
            name='inputt6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pratice_problems',
            name='inputt7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pratice_problems',
            name='inputt8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pratice_problems',
            name='inputt9',
            field=models.TextField(blank=True, null=True),
        ),
    ]
