# Generated by Django 3.2.2 on 2021-05-11 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compiler', '0004_auto_20210512_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_pratice_solution',
            name='outputt1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_pratice_solution',
            name='outputt10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_pratice_solution',
            name='outputt2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_pratice_solution',
            name='outputt3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_pratice_solution',
            name='outputt4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_pratice_solution',
            name='outputt5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_pratice_solution',
            name='outputt6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_pratice_solution',
            name='outputt7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_pratice_solution',
            name='outputt8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_pratice_solution',
            name='outputt9',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_pratice_solution',
            name='point_scored',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
