# Generated by Django 3.2.2 on 2021-05-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compiler', '0006_user_pratice_solution_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='All_Contest',
            fields=[
                ('contest_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField(null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
            ],
        ),
    ]
