# Generated by Django 3.2.2 on 2021-05-12 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Compiler', '0007_all_contest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='All_Contest',
            new_name='All_Contest_Data',
        ),
    ]
