# Generated by Django 3.2.2 on 2021-05-12 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compiler', '0008_rename_all_contest_all_contest_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all_contest_data',
            name='contest_id',
        ),
        migrations.AddField(
            model_name='all_contest_data',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
