# Generated by Django 3.2.2 on 2021-05-12 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Compiler', '0009_auto_20210512_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest_Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('long_des', models.TextField(null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('inputt1', models.TextField(blank=True, null=True)),
                ('ex_outputt1', models.TextField(blank=True, null=True)),
                ('inputt2', models.TextField(blank=True, null=True)),
                ('ex_outputt2', models.TextField(blank=True, null=True)),
                ('inputt3', models.TextField(blank=True, null=True)),
                ('ex_outputt3', models.TextField(blank=True, null=True)),
                ('inputt4', models.TextField(blank=True, null=True)),
                ('ex_outputt4', models.TextField(blank=True, null=True)),
                ('inputt5', models.TextField(blank=True, null=True)),
                ('ex_outputt5', models.TextField(blank=True, null=True)),
                ('inputt6', models.TextField(blank=True, null=True)),
                ('ex_outputt6', models.TextField(blank=True, null=True)),
                ('inputt7', models.TextField(blank=True, null=True)),
                ('ex_outputt7', models.TextField(blank=True, null=True)),
                ('inputt8', models.TextField(blank=True, null=True)),
                ('ex_outputt8', models.TextField(blank=True, null=True)),
                ('inputt9', models.TextField(blank=True, null=True)),
                ('ex_outputt9', models.TextField(blank=True, null=True)),
                ('inputt10', models.TextField(blank=True, null=True)),
                ('ex_outputt10', models.TextField(blank=True, null=True)),
                ('contest_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Compiler.all_contest_data')),
            ],
        ),
    ]
